<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.41.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\UnionUtil\UnionUtil.csproj" />
    <ProjectReference
       Include="..\src\UnionUtil.Meta\UnionUtil.Meta.csproj"
       OutputItemType="Analyzer"
       ReferenceOutputAssembly="false"
     />
  </ItemGroup>

</Project>
