// generated by claude
#nullable enable
using Test;

namespace UnionTests;

[InlineArray(4)]
public struct Small4 { private byte _b; }

[InlineArray(7)]
public struct Small7 { private byte _b; }

[InlineArray(32)]
public struct Big32 { private byte _b; }

public class ReadOnlyUnionTests {
   private const int Iterations = 2_000_000;
   private const int ThreadCount = 8;

   /// <summary>
   /// Readonly union constructed once, read concurrently from many threads.
   /// Verifies no torn reads on the immutable struct.
   /// </summary>
   [Fact]
   public async Task ConcurrentReads_SboValue_AlwaysConsistent() {
      ReadOnlyUnion<uint, long, byte> union = 0xDEAD_BEEFu;

      var violations = new long[1];

      var readers = Enumerable.Range(0, ThreadCount).Select(_ => Task.Run(() => {
         for (int i = 0; i < Iterations && Volatile.Read(ref violations[0]) == 0; i++) {
            var snap = union;
            if (!snap.TryGetValue(out uint v) || v != 0xDEAD_BEEF)
               Interlocked.Increment(ref violations[0]);
         }
      })).ToArray();

      await Task.WhenAll(readers);

      Assert.Equal(0, Volatile.Read(ref violations[0]));
   }

   /// <summary>
   /// Readonly union holding a heap-allocated type (exceeds SBO).
   /// Concurrent reads should always see the correct boxed value.
   /// </summary>
   [Fact]
   public async Task ConcurrentReads_HeapValue_AlwaysConsistent() {
      ReadOnlyUnion<uint, long, Big32> union = (long)0x0BAD_CAFE_0BAD_CAFE;

      var violations = new long[1];

      var readers = Enumerable.Range(0, ThreadCount).Select(_ => Task.Run(() => {
         for (int i = 0; i < Iterations && Volatile.Read(ref violations[0]) == 0; i++) {
            var snap = union;
            if (!snap.TryGetValue(out long v) || v != 0x0BAD_CAFE_0BAD_CAFE)
               Interlocked.Increment(ref violations[0]);
         }
      })).ToArray();

      await Task.WhenAll(readers);

      Assert.Equal(0, Volatile.Read(ref violations[0]));
   }

   /// <summary>
   /// Multiple readonly unions with different variants, all being read
   /// concurrently. Verifies the index/sbo/box fields stay consistent
   /// even when the struct is being copied across threads repeatedly.
   /// </summary>
   [Fact]
   public async Task ConcurrentReads_MultipleVariants_NoCrossContamination() {
      ReadOnlyUnion<uint, long, byte> unionA = 42u;
      ReadOnlyUnion<uint, long, byte> unionB = 99L;
      ReadOnlyUnion<uint, long, byte> unionC = (byte)0xFF;

      var violations = new long[1];

      var readers = Enumerable.Range(0, ThreadCount).Select(tid => Task.Run(() => {
         for (int i = 0; i < Iterations && Volatile.Read(ref violations[0]) == 0; i++) {
            // Each thread reads all three unions
            var a = unionA;
            var b = unionB;
            var c = unionC;

            if (!a.TryGetValue(out uint va) || va != 42u)
               Interlocked.Increment(ref violations[0]);
            else if (!b.TryGetValue(out long vb) || vb != 99L)
               Interlocked.Increment(ref violations[0]);
            else if (!c.TryGetValue(out byte vc) || vc != 0xFF)
               Interlocked.Increment(ref violations[0]);
         }
      })).ToArray();

      await Task.WhenAll(readers);

      Assert.Equal(0, Volatile.Read(ref violations[0]));
   }

   /// <summary>
   /// Concurrent reads with GC pressure. The _box field points to a
   /// managed object — verify GC relocation doesn't break anything
   /// when many threads are reading simultaneously.
   /// </summary>
   [Fact]
   public async Task ConcurrentReads_WithGcPressure_HeapValueSurvives() {
      ReadOnlyUnion<uint, long, Big32> union = (long)0x1234_5678_9ABC_DEF0;

      var violations = new long[1];

      var gcThread = Task.Run(() => {
         for (int i = 0; i < Iterations / 10 && Volatile.Read(ref violations[0]) == 0; i++) {
            // Allocate garbage and force collections
            _ = new byte[1024];
            if (i % 500 == 0)
               GC.Collect(2, GCCollectionMode.Forced, true, true);
         }
      });

      var readers = Enumerable.Range(0, ThreadCount).Select(_ => Task.Run(() => {
         for (int i = 0; i < Iterations && Volatile.Read(ref violations[0]) == 0; i++) {
            var snap = union;
            if (!snap.TryGetValue(out long v) || v != 0x1234_5678_9ABC_DEF0)
               Interlocked.Increment(ref violations[0]);
         }
      })).ToArray();

      await Task.WhenAll([gcThread, .. readers]);

      Assert.Equal(0, Volatile.Read(ref violations[0]));
   }

   /// <summary>
   /// TryGetValue for the wrong variant should always return false,
   /// never accidentally succeed due to a torn read or stale index.
   /// </summary>
   [Fact]
   public async Task ConcurrentReads_WrongVariant_AlwaysReturnsFalse() {
      ReadOnlyUnion<uint, long, byte> union = 42u; // index = 1

      var violations = new long[1];

      var readers = Enumerable.Range(0, ThreadCount).Select(_ => Task.Run(() => {
         for (int i = 0; i < Iterations && Volatile.Read(ref violations[0]) == 0; i++) {
            var snap = union;

            // These should never succeed
            if (snap.TryGetValue(out long _))
               Interlocked.Increment(ref violations[0]);
            if (snap.TryGetValue(out byte _))
               Interlocked.Increment(ref violations[0]);
         }
      })).ToArray();

      await Task.WhenAll(readers);

      Assert.Equal(0, Volatile.Read(ref violations[0]));
   }
}
