<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
     <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
     <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>

     <IsPackable>true</IsPackable>
     <PackageId>UnionUtil</PackageId>
     <Version>0.0.0</Version>
     <Authors>jipg</Authors>
     <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
     <None Include="../.,/../../README.md" Pack="true" PackagePath="/" />
     <ProjectReference
        Include="..\UnionUtil.Meta\UnionUtil.Meta.csproj" 
        OutputItemType="Analyzer"
        ReferenceOutputAssembly="false"
      />
     <Content
        Include="..\UnionUtil.Meta\bin\$(Configuration)\netstandard2.0\UnionUtil.Meta.dll"
        Pack="true"
        PackagePath="analyzers/dotnet/cs/"
      />
  </ItemGroup>

</Project>
