<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
     <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
     <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
     <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>

     <IsPackable>true</IsPackable>
     <PackageId>UnionUtil</PackageId>
     <Version>0.0.1</Version>
     <Authors>jipg</Authors>
     <PackageLicenseExpression>MIT</PackageLicenseExpression>
     <RepositoryUrl>https://github.com/jipgg/unionutil</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
     <None Include="../.,/../../README.md" Pack="true" PackagePath="/" />
     <ProjectReference
        Include="..\generators\generators.csproj" 
        OutputItemType="Analyzer"
        ReferenceOutputAssembly="false"
      />
     <ProjectReference
        Include="..\internal_generators\internal_generators.csproj" 
        OutputItemType="Analyzer"
        ReferenceOutputAssembly="false"
      />
     <Content
        Include="..\generators\bin\$(Configuration)\netstandard2.0\generators.dll"
        Pack="true"
        PackagePath="analyzers/dotnet/cs/"
      />
  </ItemGroup>

</Project>
